name: 'Deploy'

on:
  push:
    branches:
      - master


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Dryrun
        uses: artronics/terraform-flow-action@v1
        with:
          path: terraform
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
