name: 'Deploy'

on:
  push:
    branches:
      - '!master'


jobs:
  dry-run:
    name: Dry Run
    runs-on: ubuntu-latest
    container: hashicorp/terraform

    env:
      PR_NO: ${{ github.event.pull_request.number }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: |
          echo github.event.number = ${{ github.event.number  }}
          echo github.event.pull_request.number = ${{ github.event.pull_request.number }}
          echo github.event.issue.number = ${{ github.event.issue.number }}
        name: check

      - name: Terraform init
        run: terraform init
        working-directory: terraform

      - name: Terraform apply
        run: |
          terraform apply -auto-approve
        working-directory: terraform
