name: 'Pull Request'

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  dry-run:
    name: Dry Run
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Dryrun
        uses: artronics/terraform-flow-action@v1
        with:
          path: terraform
          dryrun: true
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

