name: 'Pull Request'

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  dry-run:
    name: Dry Run
    runs-on: ubuntu-latest
    container: hashicorp/terraform

    env:
      PR_NO: ${{ github.event.pull_request.number }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: |
          echo github.event.number = ${{ github.event.number  }}
          echo github.event.pull_request.number = ${{ github.event.pull_request.number }}
          echo github.event.issue.number = ${{ github.event.issue.number }}
        name: check

      - name: Terraform init
        run: terraform init
        working-directory: terraform

      - name: Terraform plan
        run: terraform plan -var='environment=dev'
        working-directory: terraform

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push pipeline image
        uses: docker/build-push-action@v3
        with:
          context: "./docker"
          file: docker/pipeline.Dockerfile
          push: true
          tags: "user/app:latest, user/app:0.1.0-test"
